pipeline {
    agent any
 
    tools {
        maven "maven"
        jdk "jdk"
    }
 
    stages {
        stage('Initialize'){
            steps{
                echo "PATH = ${M2_HOME}/bin:${PATH}"
                echo "M2_HOME = /opt/maven"
            }
        }
       stage('Build') {
           steps {
               sh 'mvn clean package' // Build the application using Maven
           }
       }
       stage('Test') {
           steps {
               sh 'mvn test' // Run unit tests using Maven
           }
       }
   }
}
