pipeline {
    agent any
 
    tools {
        maven "maven"
        jdk "jdk"
    }
 
    stages {
       stage('Build') {
           steps {
               sh 'mvn clean package' // Build the application using Maven
           }
       }
       stage('Test') {
           steps {
               sh 'mvn test' // Run unit tests using Maven
           }
       }
   }
}
